/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Models.Interfaces;

import Models.Calzado;
import Models.CalzadoDAO;
import Models.Cliente;
import Models.ClienteDAO;
import Models.ConexionDB;
import Models.Empleado;
import Models.EmpleadoDAO;
import Models.Factura;
import Models.FacturaDAO;
import Models.Renglon;
import Models.RenglonDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Octavio
 */
public class PanelVenta extends javax.swing.JFrame {

private DefaultTableModel model;
    /**
     *
     */
public PanelVenta(List<Empleado> empleados,List<Calzado> calzados, List<Cliente> clientes) {
    initComponents(); 
    ComboBoxCliente.setEditable(true);
    ComboBoxEmpleado.setEditable(true);
    ComboBoxCalzado.setEditable(true);
model = new DefaultTableModel();
model.setColumnIdentifiers(new Object[]{"Indice", "Código", "Descripción", "Marca", "Precio Venta", "Cantidad", "Total"});
TablaVenta.setModel(model);
   btnConfirmarVenta.setEnabled(false);
    cargarEmpleados(empleados); 
    cargarCalzados(calzados);
    cargarClientes(clientes);
}
public void cargarCalzados(List<Calzado> calzados){
   ComboBoxCalzado.removeAllItems(); 

    for (Calzado a: calzados) {
        ComboBoxCalzado.addItem(a.getCodigo()+(" ")+a.getMarca()+(" ")+a.getDescripcion()+(" ")+a.getTalle()+(" ")+("$")+a.getPrecioVenta()); // Agrega el nombre al combo
    }
}
public void cargarClientes(List<Cliente> clientes){
   ComboBoxCliente.removeAllItems(); 

    for (Cliente c: clientes) {
        ComboBoxCliente.addItem(c.getNombre()+(" ")+c.getDNI_CUIL()); 
    }
}
public void cargarEmpleados(List<Empleado> empleados) {
    ComboBoxEmpleado.removeAllItems();

    for (Empleado e : empleados) {
        ComboBoxEmpleado.addItem(e.getNombre() + " " + e.getDni());
 
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVenta = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxEmpleado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxCliente = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ComboBoxCalzado = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnConfirmarVenta = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 255));

        TablaVenta.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        TablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Indice", "Codigo Calzado", "Descripcion", "Marca", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane2.setViewportView(TablaVenta);

        jButton4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 0));
        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192)
                .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel2.setText("Seleccione el Cliente que esta comprando:");

        ComboBoxEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxEmpleadoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setText("Seleccione el Empleado que realiza la venta:");

        ComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel1.setText("Seleccione el/los Calzados que lleva el cliente");

        ComboBoxCalzado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxCalzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxCalzadoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setText("Confirmar Calzado");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton2.setText("Calcular Total:");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton5.setText("Realizar Pago");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        btnConfirmarVenta.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        btnConfirmarVenta.setForeground(new java.awt.Color(0, 204, 0));
        btnConfirmarVenta.setText("Confirmar Venta");
        btnConfirmarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComboBoxCalzado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addComponent(ComboBoxEmpleado, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBoxEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxCalzado, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConfirmarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxEmpleadoActionPerformed
       
    }//GEN-LAST:event_ComboBoxEmpleadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
DefaultTableModel model = (DefaultTableModel) TablaVenta.getModel();

    Object itemCalzado = ComboBoxCalzado.getEditor().getItem();
    String textoCombo = itemCalzado != null ? itemCalzado.toString().trim() : "";

    if (textoCombo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Debe seleccionar o escribir un calzado.");
        return;
    }

    String[] partes = textoCombo.split(" ");
    if (partes.length == 0) {
        JOptionPane.showMessageDialog(null, "Formato inválido de selección.");
        return;
    }

    String codigo = partes[0]; 

    CalzadoDAO calzadoDAO = new CalzadoDAO();
    Calzado calzado = calzadoDAO.buscarCalzado(codigo);

    if (calzado == null) {
        JOptionPane.showMessageDialog(null, "Calzado no encontrado en la base de datos.");
        return;
    }

    boolean encontrado = false;
    for (int i = 0; i < model.getRowCount(); i++) {
        String codigoTabla = model.getValueAt(i, 1).toString();

        if (codigo.equals(codigoTabla)) {
            int cantidad = Integer.parseInt(model.getValueAt(i, 5).toString());
            cantidad++;

            model.setValueAt(cantidad, i, 5);
            model.setValueAt(calzado.getPrecioVenta() * cantidad, i, 6);
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        int indice = model.getRowCount() + 1;
        Object[] fila = new Object[]{
            indice,
            calzado.getCodigo(),
            calzado.getDescripcion(),
            calzado.getMarca(),
            calzado.getPrecioVenta(),
            1,
            calzado.getPrecioVenta()
        };
        model.addRow(fila);
    }
    calzadoDAO.descontarStock(codigo);

    List<Calzado> listaActualizada = calzadoDAO.obtenerTodos();
    cargarCalzados(listaActualizada);

    ComboBoxCalzado.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
double total = 0.0;

DefaultTableModel model = (DefaultTableModel) TablaVenta.getModel();

for (int i = 0; i < model.getRowCount(); i++) {

    Object valorTotal = model.getValueAt(i, 6); 

    String totalStr = valorTotal.toString().replace("$", "").replace(",", "").trim();

    try {
        double subtotal = Double.parseDouble(totalStr);
        total += subtotal;
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error al convertir el total en la fila " + (i + 1));
    }
}


jTextField1.setText(String.format("$%.2f", total));     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ComboBoxCalzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxCalzadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxCalzadoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) TablaVenta.getModel();
    
    if (model.getRowCount() > 0) {
        CalzadoDAO calzadoDAO = new CalzadoDAO();

        for (int i = 0; i < model.getRowCount(); i++) {
            int codigo = Integer.parseInt(model.getValueAt(i, 1).toString()); // Código
            int cantidad = Integer.parseInt(model.getValueAt(i, 5).toString()); // Cantidad
            
            try {
                calzadoDAO.sumarStock(codigo, cantidad); // Esta función la explico abajo
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al restaurar stock del calzado con código: " + codigo);
            }
        }
    }

    this.dispose();
    PantallaPrincipal v1 = new PantallaPrincipal();
    v1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
 int filas = TablaVenta.getRowCount();

if (filas == 0) {
    
    JOptionPane.showMessageDialog(this, "Debe agregar productos antes de pagar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
} else {
    
    int respuesta = JOptionPane.showConfirmDialog(this, 
            "¿Confirmar realización de pago correctamente?", 
            "Confirmación de Pago", 
            JOptionPane.YES_NO_OPTION);

    if (respuesta == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Pago realizado con éxito");
        btnConfirmarVenta.setEnabled(true);
    } else {
        JOptionPane.showMessageDialog(this, "Pago no realizado");
    }
}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnConfirmarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVentaActionPerformed
                                                  
    DefaultTableModel model = (DefaultTableModel) TablaVenta.getModel();

    if (model.getRowCount() == 0) {
        JOptionPane.showMessageDialog(null, "No hay calzados en la venta.");
        return;
    }

    
    Object itemCliente = ComboBoxCliente.getEditor().getItem();
    String clienteRaw = itemCliente != null ? itemCliente.toString().trim() : "";
    String posibleDNICliente = clienteRaw.replaceAll(".*?(\\d+)$", "$1");

    ClienteDAO clienteDAO = new ClienteDAO();
    Cliente cliente = clienteDAO.buscarCliente(posibleDNICliente);

    if (cliente == null) {
        JOptionPane.showMessageDialog(null, "Cliente no encontrado en la base de datos.");
        return;
    }

    
    Object itemEmpleado = ComboBoxEmpleado.getEditor().getItem();
    String empleadoRaw = itemEmpleado != null ? itemEmpleado.toString().trim() : "";
    String posibleDNIEmpleado = empleadoRaw.replaceAll(".*?(\\d+)$", "$1");

    EmpleadoDAO empleadoDAO = new EmpleadoDAO();
    Empleado empleado = empleadoDAO.buscarEmpleado(posibleDNIEmpleado);

    if (empleado == null) {
        JOptionPane.showMessageDialog(null, "Empleado no encontrado en la base de datos.");
        return;
    }

  
    int cantidadTotal = 0;
    double totalFinal = 0.0;
    List<Renglon> renglones = new ArrayList<>();
    CalzadoDAO calzadoDAO = new CalzadoDAO();

    for (int i = 0; i < model.getRowCount(); i++) {
        int cantidad = Integer.parseInt(model.getValueAt(i, 5).toString());
        double total = Double.parseDouble(model.getValueAt(i, 6).toString());

        cantidadTotal += cantidad;
        totalFinal += total;

        String codigo = model.getValueAt(i, 1).toString();

        Renglon r = new Renglon();
        r.setCantidad(cantidad);
        r.setTotal(total);

        Calzado calzado = calzadoDAO.buscarCalzado(codigo);
        r.setCalzado(calzado);

        renglones.add(r);
    }

    try {
        
        Factura factura = new Factura();
        factura.setCantidad(cantidadTotal);
        factura.setTotal(totalFinal);
        factura.setCliente(cliente);

        FacturaDAO facturaDAO = new FacturaDAO();
        int idGenerado = facturaDAO.insertarFacturaYRetornarID(factura);
        factura.setId(idGenerado);

        RenglonDAO renglonDAO = new RenglonDAO();
        for (Renglon r : renglones) {
            r.setFactura(factura);
            renglonDAO.insertar(r);
        }

        
        StringBuilder mensaje = new StringBuilder();
        mensaje.append("✅ Venta registrada con éxito\n");
        mensaje.append("🧾 ID de Factura: ").append(idGenerado).append("  |  Total: $").append(String.format("%.2f", totalFinal)).append("\n");
        mensaje.append("📦 Productos:\n");

        for (Renglon r : renglones) {
            mensaje.append("• Código: ").append(r.getCalzado().getCodigo())
                   .append(" | Descripción: ").append(r.getCalzado().getDescripcion())
                   .append(" | Cantidad: ").append(r.getCantidad())
                   .append(" | Total: $").append(String.format("%.2f", r.getTotal()))
                   .append("\n");
        }

        int opcion = JOptionPane.showOptionDialog(
                null,
                mensaje.toString(),
                "Factura registrada",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                new Object[]{"Imprimir factura", "Cerrar"},
                "Imprimir factura"
        );

        if (opcion == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "🖨 Imprimiendo...");
        }

        model.setRowCount(0);
        this.dispose();
        new PantallaPrincipal().setVisible(true);

    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al registrar la venta.");
    }

    }//GEN-LAST:event_btnConfirmarVentaActionPerformed

    private void ComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxClienteActionPerformed

    /**
     * @param args the command line arguments
     */
public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            List<Empleado> listaVacia = new ArrayList<>();
            List<Calzado> listaVacia2=new ArrayList<>();
              List<Cliente> listaVacia3=new ArrayList<>();
            new PanelVenta(listaVacia,listaVacia2,listaVacia3).setVisible(true);
        }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCalzado;
    private javax.swing.JComboBox<String> ComboBoxCliente;
    private javax.swing.JComboBox<String> ComboBoxEmpleado;
    private javax.swing.JTable TablaVenta;
    private javax.swing.JButton btnConfirmarVenta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
